# Generated by Django 5.2.7 on 2026-05-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('asset_issued', 'Выдача ТМЦ'), ('asset_returned', 'Возврат ТМЦ'), ('asset_updated', 'Карточка ТМЦ обновлена'), ('transfer_requested', 'Запрос на передачу'), ('transfer_approved', 'Передача подтверждена'), ('transfer_rejected', 'Передача отклонена'), ('asset_verified', 'Сверка ТМЦ'), ('asset_written_off', 'Списание ТМЦ'), ('inventory_assignment_created', 'Назначена инвентаризация'), ('inventory_assignment_revoked', 'Инвентаризация отозвана')], max_length=50),
        ),
    ]
