# Generated by Django 5.2.7 on 2026-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='Сотрудник', max_length=20),
        ),
    ]
